type: unet
kwargs:
  down_block_types: [CrossAttnDownBlockSpatioTemporal, CrossAttnDownBlockSpatioTemporal, CrossAttnDownBlockSpatioTemporal] #, DownBlockSpatioTemporal]
  up_block_types:   [UpBlockSpatioTemporal, UpBlockSpatioTemporal, UpBlockSpatioTemporal] #, CrossAttnUpBlockSpatioTemporal]
  block_out_channels: [32, 96, 128] #, 192]   # must be divisible by 32
  num_attention_heads: [1, 3, 4] #, 6]      # per-head dims = [16,16,16,16]
  cross_attention_dim: 1
  layers_per_block: 2
  transformer_layers_per_block: 1
