type: unet
kwargs:
  down_block_types: [CrossAttnDownBlockSpatioTemporal, CrossAttnDownBlockSpatioTemporal, CrossAttnDownBlockSpatioTemporal,DownBlockSpatioTemporal]
  up_block_types: [UpBlockSpatioTemporal, UpBlockSpatioTemporal, UpBlockSpatioTemporal, CrossAttnUpBlockSpatioTemporal]
  block_out_channels: [64, 192, 288, 384]
  num_attention_heads: [8, 16, 24, 32]
  cross_attention_dim: 1
  layers_per_block: 2
  transformer_layers_per_block: 1
