defaults:
  - _self_ # First takes priority so any properties redefined here take precedence
  - paths: ibme_cluster # Simply override in cli call


real_data_path: ${paths.data_path}/CAMUS_Processed_Frames #_Temp_2 #Frames
repo_id: HReynaud/EchoFlow
fps_metadata_csv: ${paths.data_path}/CAMUS_Latents_{vae_res}/metadata.csv # CSV with video_name and FPS column to override default FPS


run_dir: ${paths.train_output_path}/sweep_vaes/mean/r05/4f8_eps0always
output_dir: ${run_dir}/mid_train_evaluation


types:
  #- framewise
  #- videowise
  - framewise_no_pad
  #- videowise_no_pad
  #- framewise_generated
  #- videowise_generated
  #- framewise_stitched
  #- videowise_stitched

metrics:
  real_glob: ['*']            # glob pattern to match real videos
  fake_glob: ['*']            # glob pattern to match generated videos
  pairwise_metrics: [ssim, psnr, lpips_vgg, mae, mse]  # metrics to compute
  stylegan_metrics: [fid50k_full, fvd2048_10f]

hydra:
  run:
    dir: ${paths.train_output_path}/mid_train_eval_outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}