run_dirs:
  - ${paths.train_output_path}/tests/2025-11-18/18-54-47
  - ${paths.train_output_path}/tests/2025-11-19/15-41-40

override_old_run: true  # Whether to skip sampling if latents already exist
n_inference_steps: [2, 4, 8, 16, 32]
output_dir: ${paths.train_output_path}/multi_run_evaluation #/${now:%Y-%m-%d_%H-%M-%S}